"""
Schema 模块

包含所有 Pydantic 模型定义。
"""

from .common import (
    ApiResponse,
    PaginatedResponse,
    PageParams,
    TimestampMixin,
    IdMixin,
    BaseSchema,
)
from .platforms import (
    PlatformCreate,
    PlatformUpdate,
    PlatformResponse,
    PlatformTreeResponse,
)
from .auth import (
    LoginRequest,
    UsernamePasswordLoginRequest,
    TokenResponse,
    UserInfo,
    LoginResponse,
    ChangePasswordRequest,
    UpdateDisplayNameRequest,
    RefreshTokenRequest,
)
from .users import (
    SuperAdminBase,
    SuperAdminCreate,
    SuperAdminUpdate,
    SuperAdminResponse,
    OperatorBase,
    OperatorCreate,
    OperatorUpdate,
    OperatorResponse,
    SubUserBase,
    SubUserCreate,
    SubUserUpdate,
    SubUserResponse,
    UserTagBase,
    UserTagCreate,
    UserTagUpdate,
    UserTagResponse,
    UserTransferRequest,
    ResetPasswordRequest,
)
from .templates import (
    TemplatePlatformBase,
    TemplatePlatformCreate,
    TemplatePlatformUpdate,
    TemplatePlatformResponse,
    TemplateCategoryBase,
    TemplateCategoryCreate,
    TemplateCategoryUpdate,
    TemplateCategoryResponse,
    TemplateTagBase,
    TemplateTagCreate,
    TemplateTagUpdate,
    TemplateTagResponse,
    TemplateBase,
    TemplateCreate,
    TemplateUpdate,
    TemplateResponse,
    TemplateCopyRequest,
)
from .materials import (
    MaterialCategoryBase,
    MaterialCategoryCreate,
    MaterialCategoryUpdate,
    MaterialCategoryResponse,
    MaterialTagBase,
    MaterialTagCreate,
    MaterialTagUpdate,
    MaterialTagResponse,
    MaterialAttachmentBase,
    MaterialAttachmentCreate,
    MaterialAttachmentUpdate,
    MaterialAttachmentResponse,
    MaterialBase,
    MaterialCreate,
    MaterialUpdate,
    MaterialResponse,
    MaterialCopyRequest,
)
from .generation import (
    GenerationTaskBase,
    GenerationTaskCreate,
    GenerationTaskUpdate,
    GenerationTaskResponse,
    GenerationItemBase,
    GenerationItemUpdate,
    GenerationItemResponse,
    GenerationTaskProgressLogResponse,
    BatchRetryRequest,
    BatchPauseRequest,
)
from .trend_analysis import (
    TimeDimension,
    CompareType,
    ContentType,
    TrendDataPoint,
    ComparisonData,
    GenerationTrendResponse,
    DistributionTrendResponse,
    PublishTrendResponse,
    OperatorTrendItem,
    OperatorTrendResponse,
    TrendAnalysisFilterOptions,
)
from .scheduled_task import (
    ScheduledTaskCreate,
    ScheduledTaskUpdate,
    ScheduledTaskResponse,
    ScheduledTaskBrief,
    ScheduledTaskExecuteNow,
)

__all__ = [
    # Common
    "ApiResponse",
    "PaginatedResponse",
    "PageParams",
    "TimestampMixin",
    "IdMixin",
    "BaseSchema",
    # Platforms
    "PlatformCreate",
    "PlatformUpdate",
    "PlatformResponse",
    "PlatformTreeResponse",
    # Auth
    "LoginRequest",
    "UsernamePasswordLoginRequest",
    "TokenResponse",
    "UserInfo",
    "LoginResponse",
    "ChangePasswordRequest",
    "UpdateDisplayNameRequest",
    "RefreshTokenRequest",
    # Users
    "SuperAdminBase",
    "SuperAdminCreate",
    "SuperAdminUpdate",
    "SuperAdminResponse",
    "OperatorBase",
    "OperatorCreate",
    "OperatorUpdate",
    "OperatorResponse",
    "SubUserBase",
    "SubUserCreate",
    "SubUserUpdate",
    "SubUserResponse",
    "UserTagBase",
    "UserTagCreate",
    "UserTagUpdate",
    "UserTagResponse",
    "UserTransferRequest",
    "ResetPasswordRequest",
    # Templates
    "TemplatePlatformBase",
    "TemplatePlatformCreate",
    "TemplatePlatformUpdate",
    "TemplatePlatformResponse",
    "TemplateCategoryBase",
    "TemplateCategoryCreate",
    "TemplateCategoryUpdate",
    "TemplateCategoryResponse",
    "TemplateTagBase",
    "TemplateTagCreate",
    "TemplateTagUpdate",
    "TemplateTagResponse",
    "TemplateBase",
    "TemplateCreate",
    "TemplateUpdate",
    "TemplateResponse",
    "TemplateCopyRequest",
    # Materials
    "MaterialCategoryBase",
    "MaterialCategoryCreate",
    "MaterialCategoryUpdate",
    "MaterialCategoryResponse",
    "MaterialTagBase",
    "MaterialTagCreate",
    "MaterialTagUpdate",
    "MaterialTagResponse",
    "MaterialAttachmentBase",
    "MaterialAttachmentCreate",
    "MaterialAttachmentUpdate",
    "MaterialAttachmentResponse",
    "MaterialBase",
    "MaterialCreate",
    "MaterialUpdate",
    "MaterialResponse",
    "MaterialCopyRequest",
    # Generation
    "GenerationTaskBase",
    "GenerationTaskCreate",
    "GenerationTaskUpdate",
    "GenerationTaskResponse",
    "GenerationItemBase",
    "GenerationItemUpdate",
    "GenerationItemResponse",
    "GenerationTaskProgressLogResponse",
    "BatchRetryRequest",
    "BatchPauseRequest",
    # Trend Analysis
    "TimeDimension",
    "CompareType",
    "ContentType",
    "TrendDataPoint",
    "ComparisonData",
    "GenerationTrendResponse",
    "DistributionTrendResponse",
    "PublishTrendResponse",
    "OperatorTrendItem",
    "OperatorTrendResponse",
    "TrendAnalysisFilterOptions",
    # Scheduled Task
    "ScheduledTaskCreate",
    "ScheduledTaskUpdate",
    "ScheduledTaskResponse",
    "ScheduledTaskBrief",
    "ScheduledTaskExecuteNow",
]
