"""
Schema 模块

包含所有 Pydantic 模型定义。
"""

from .auth import (ChangePasswordRequest, LoginRequest, LoginResponse,
                   RefreshTokenRequest, TokenResponse,
                   UpdateDisplayNameRequest, UserInfo,
                   UsernamePasswordLoginRequest)
from .common import (ApiResponse, BaseSchema, IdMixin, PageParams,
                     PaginatedResponse, TimestampMixin)
from .generation import (BatchPauseRequest, BatchRetryRequest,
                         GenerationItemBase, GenerationItemResponse,
                         GenerationItemUpdate, GenerationTaskBase,
                         GenerationTaskCreate,
                         GenerationTaskProgressLogResponse,
                         GenerationTaskResponse, GenerationTaskUpdate)
from .materials import (MaterialAttachmentBase, MaterialAttachmentCreate,
                        MaterialAttachmentResponse, MaterialAttachmentUpdate,
                        MaterialBase, MaterialCategoryBase,
                        MaterialCategoryCreate, MaterialCategoryResponse,
                        MaterialCategoryUpdate, MaterialCopyRequest,
                        MaterialCreate, MaterialResponse, MaterialTagBase,
                        MaterialTagCreate, MaterialTagResponse,
                        MaterialTagUpdate, MaterialUpdate)
from .platforms import (PlatformCreate, PlatformResponse, PlatformTreeResponse,
                        PlatformUpdate)
from .scheduled_task import (ScheduledTaskBrief, ScheduledTaskCreate,
                             ScheduledTaskExecuteNow, ScheduledTaskResponse,
                             ScheduledTaskUpdate)
from .templates import (TemplateBase, TemplateCategoryBase,
                        TemplateCategoryCreate, TemplateCategoryResponse,
                        TemplateCategoryUpdate, TemplateCopyRequest,
                        TemplateCreate, TemplatePlatformBase,
                        TemplatePlatformCreate, TemplatePlatformResponse,
                        TemplatePlatformUpdate, TemplateResponse,
                        TemplateTagBase, TemplateTagCreate,
                        TemplateTagResponse, TemplateTagUpdate, TemplateUpdate)
from .trend_analysis import (CompareType, ComparisonData, ContentType,
                             DistributionTrendResponse,
                             GenerationTrendResponse, OperatorTrendItem,
                             OperatorTrendResponse, PublishTrendResponse,
                             TimeDimension, TrendAnalysisFilterOptions,
                             TrendDataPoint)
from .users import (OperatorBase, OperatorCreate, OperatorResponse,
                    OperatorUpdate, ResetPasswordRequest, SubUserBase,
                    SubUserCreate, SubUserResponse, SubUserUpdate,
                    SuperAdminBase, SuperAdminCreate, SuperAdminResponse,
                    SuperAdminUpdate, UserTagBase, UserTagCreate,
                    UserTagResponse, UserTagUpdate, UserTransferRequest)

__all__ = [
    # Common
    "ApiResponse",
    "PaginatedResponse",
    "PageParams",
    "TimestampMixin",
    "IdMixin",
    "BaseSchema",
    # Platforms
    "PlatformCreate",
    "PlatformUpdate",
    "PlatformResponse",
    "PlatformTreeResponse",
    # Auth
    "LoginRequest",
    "UsernamePasswordLoginRequest",
    "TokenResponse",
    "UserInfo",
    "LoginResponse",
    "ChangePasswordRequest",
    "UpdateDisplayNameRequest",
    "RefreshTokenRequest",
    # Users
    "SuperAdminBase",
    "SuperAdminCreate",
    "SuperAdminUpdate",
    "SuperAdminResponse",
    "OperatorBase",
    "OperatorCreate",
    "OperatorUpdate",
    "OperatorResponse",
    "SubUserBase",
    "SubUserCreate",
    "SubUserUpdate",
    "SubUserResponse",
    "UserTagBase",
    "UserTagCreate",
    "UserTagUpdate",
    "UserTagResponse",
    "UserTransferRequest",
    "ResetPasswordRequest",
    # Templates
    "TemplatePlatformBase",
    "TemplatePlatformCreate",
    "TemplatePlatformUpdate",
    "TemplatePlatformResponse",
    "TemplateCategoryBase",
    "TemplateCategoryCreate",
    "TemplateCategoryUpdate",
    "TemplateCategoryResponse",
    "TemplateTagBase",
    "TemplateTagCreate",
    "TemplateTagUpdate",
    "TemplateTagResponse",
    "TemplateBase",
    "TemplateCreate",
    "TemplateUpdate",
    "TemplateResponse",
    "TemplateCopyRequest",
    # Materials
    "MaterialCategoryBase",
    "MaterialCategoryCreate",
    "MaterialCategoryUpdate",
    "MaterialCategoryResponse",
    "MaterialTagBase",
    "MaterialTagCreate",
    "MaterialTagUpdate",
    "MaterialTagResponse",
    "MaterialAttachmentBase",
    "MaterialAttachmentCreate",
    "MaterialAttachmentUpdate",
    "MaterialAttachmentResponse",
    "MaterialBase",
    "MaterialCreate",
    "MaterialUpdate",
    "MaterialResponse",
    "MaterialCopyRequest",
    # Generation
    "GenerationTaskBase",
    "GenerationTaskCreate",
    "GenerationTaskUpdate",
    "GenerationTaskResponse",
    "GenerationItemBase",
    "GenerationItemUpdate",
    "GenerationItemResponse",
    "GenerationTaskProgressLogResponse",
    "BatchRetryRequest",
    "BatchPauseRequest",
    # Trend Analysis
    "TimeDimension",
    "CompareType",
    "ContentType",
    "TrendDataPoint",
    "ComparisonData",
    "GenerationTrendResponse",
    "DistributionTrendResponse",
    "PublishTrendResponse",
    "OperatorTrendItem",
    "OperatorTrendResponse",
    "TrendAnalysisFilterOptions",
    # Scheduled Task
    "ScheduledTaskCreate",
    "ScheduledTaskUpdate",
    "ScheduledTaskResponse",
    "ScheduledTaskBrief",
    "ScheduledTaskExecuteNow",
]
