"""initial migration

Revision ID: 6cf171e7d573
Revises: 
Create Date: 2026-04-08 23:30:59.878703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf171e7d573'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanup_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('rule_name', sa.String(length=255), nullable=False, comment='规则名称'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='内容类型'),
    sa.Column('retention_period', sa.Enum('month', 'quarter', 'year', name='retention_period_enum'), nullable=False, comment='保留期：month / quarter / year'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True, comment='上次执行时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('super_admin',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('userid', sa.String(length=64), nullable=False, comment='用户ID（登录用）'),
    sa.Column('nickname', sa.String(length=100), nullable=False, comment='管理员昵称'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('wechat_openid', sa.String(length=100), nullable=True, comment='微信OpenID'),
    sa.Column('wechat_unionid', sa.String(length=100), nullable=True, comment='微信UnionID'),
    sa.Column('status', sa.Enum('active', 'disabled', name='super_admin_status_enum'), nullable=False, comment='状态：active（正常）/ disabled（已禁用）'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_password_changed_at', sa.DateTime(), nullable=True, comment='最后密码修改时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admin_status'), 'super_admin', ['status'], unique=False)
    op.create_index(op.f('ix_super_admin_userid'), 'super_admin', ['userid'], unique=True)
    op.create_table('template_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='标签名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='标签描述'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='标签颜色'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='创建者管理员ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='标签名称'),
    sa.Column('tag_type', sa.Enum('operator_tag', 'subuser_tag', name='user_tag_type_enum'), nullable=False, comment='标签类型：operator_tag（运营管理员标签）/ subuser_tag（子用户标签）'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='标签颜色'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='创建者用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('platform', sa.String(length=100), nullable=False, comment='平台：bailian / yuanbao / moonshot / zhipu / doubao / jimeng / kling'),
    sa.Column('model_id', sa.String(length=255), nullable=False, comment='模型ID'),
    sa.Column('model_name', sa.String(length=255), nullable=False, comment='模型名称'),
    sa.Column('model_type', sa.Enum('llm', 'image', 'video', name='model_type_enum'), nullable=False, comment='模型类型：llm / image / video'),
    sa.Column('base_url', sa.String(length=500), nullable=True, comment='【大语言模型专属】Base URL'),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True, comment='API端点'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认'),
    sa.Column('max_concurrency', sa.Integer(), nullable=False, comment='最大并发数'),
    sa.Column('config_json', sa.JSON(), nullable=True, comment='配置JSON（包含API Key等）'),
    sa.Column('status', sa.Enum('active', 'inactive', name='model_config_status_enum'), nullable=False, comment='状态：active / inactive'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否系统预置模型'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者超级管理员ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['super_admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者超级管理员ID'),
    sa.Column('userid', sa.String(length=64), nullable=False, comment='用户ID（登录用）'),
    sa.Column('nickname', sa.String(length=100), nullable=False, comment='【管理备注名】超级管理员备注名'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='【自定义昵称】运营管理员自定义昵称'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('wechat_openid', sa.String(length=100), nullable=True, comment='微信OpenID'),
    sa.Column('wechat_unionid', sa.String(length=100), nullable=True, comment='微信UnionID'),
    sa.Column('status', sa.Enum('online', 'offline', 'disabled', name='operator_status_enum'), nullable=False, comment='状态：online（在线）/ offline（已离线）/ disabled（已禁用）'),
    sa.Column('user_positioning', sa.String(length=255), nullable=True, comment='账号的自媒体运营定位'),
    sa.Column('user_category', sa.String(length=100), nullable=True, comment='账号的运营分类'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_password_changed_at', sa.DateTime(), nullable=True, comment='最后密码修改时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['super_admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_created_by'), 'operator', ['created_by'], unique=False)
    op.create_index(op.f('ix_operator_status'), 'operator', ['status'], unique=False)
    op.create_index(op.f('ix_operator_userid'), 'operator', ['userid'], unique=True)
    op.create_table('user_tag_rel',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('tag_id', sa.BigInteger(), nullable=False, comment='标签ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['tag_id'], ['user_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='素材标题（拟题）'),
    sa.Column('text_content', sa.Text(), nullable=True, comment='文本内容'),
    sa.Column('source_url', sa.String(length=500), nullable=True, comment='来源URL'),
    sa.Column('source_type', sa.Enum('upload', 'link', 'description', name='material_source_type_enum'), nullable=False, comment='来源类型：upload（上传）/ link（链接）/ description（描述）'),
    sa.Column('content_type', sa.Enum('text', 'image_text', 'video_text', 'mix', name='material_content_type_enum'), nullable=False, comment='内容类型：text（纯文本）/ image_text（图文）/ video_text（视频）/ mix（混合）'),
    sa.Column('image_count', sa.Integer(), nullable=False, comment='图片数量（冗余字段，提高查询效率）'),
    sa.Column('video_count', sa.Integer(), nullable=False, comment='视频数量（冗余字段，提高查询效率）'),
    sa.Column('status', sa.Enum('available', 'disabled', name='material_status_enum'), nullable=False, comment='状态：available（可用）/ disabled（已禁用）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='上传者运营管理员ID'),
    sa.Column('owner_operator_id', sa.BigInteger(), nullable=False, comment='所属运营管理员ID（数据隔离用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['owner_operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_owner_operator_id'), 'material', ['owner_operator_id'], unique=False)
    op.create_table('material_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='标签名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='标签描述'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='标签颜色'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者运营管理员ID'),
    sa.Column('owner_operator_id', sa.BigInteger(), nullable=False, comment='所属运营管理员ID（数据隔离用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['owner_operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_tag_owner_operator_id'), 'material_tag', ['owner_operator_id'], unique=False)
    op.create_table('sub_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('owner_operator_id', sa.BigInteger(), nullable=False, comment='所属运营管理员ID（数据隔离用）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者运营管理员ID'),
    sa.Column('managed_by', sa.BigInteger(), nullable=True, comment='当前管理者运营管理员ID（支持转移）'),
    sa.Column('userid', sa.String(length=64), nullable=False, comment='用户ID（登录用）'),
    sa.Column('nickname', sa.String(length=100), nullable=False, comment='【管理备注名】运营管理员备注名'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='【自定义昵称】子用户自定义昵称'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('wechat_openid', sa.String(length=100), nullable=True, comment='微信OpenID'),
    sa.Column('wechat_unionid', sa.String(length=100), nullable=True, comment='微信UnionID'),
    sa.Column('status', sa.Enum('online', 'offline', 'disabled', name='sub_user_status_enum'), nullable=False, comment='状态：online（在线）/ offline（已离线）/ disabled（已禁用）'),
    sa.Column('user_positioning', sa.String(length=255), nullable=True, comment='账号的自媒体运营定位'),
    sa.Column('user_category', sa.String(length=100), nullable=True, comment='账号的运营分类'),
    sa.Column('content_style', sa.String(length=255), nullable=True, comment='【子用户专属】文案风格'),
    sa.Column('account_type', sa.String(length=255), nullable=True, comment='【子用户专属】账号类型'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_password_changed_at', sa.DateTime(), nullable=True, comment='最后密码修改时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['managed_by'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['owner_operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_user_managed_by'), 'sub_user', ['managed_by'], unique=False)
    op.create_index(op.f('ix_sub_user_owner_operator_id'), 'sub_user', ['owner_operator_id'], unique=False)
    op.create_index(op.f('ix_sub_user_status'), 'sub_user', ['status'], unique=False)
    op.create_index(op.f('ix_sub_user_userid'), 'sub_user', ['userid'], unique=True)
    op.create_table('template_platform',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='平台名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='平台描述'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='平台颜色'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者运营管理员ID'),
    sa.Column('owner_operator_id', sa.BigInteger(), nullable=False, comment='所属运营管理员ID（数据隔离用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['owner_operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_platform_owner_operator_id'), 'template_platform', ['owner_operator_id'], unique=False)
    op.create_table('generation_task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('material_id', sa.BigInteger(), nullable=True, comment='使用的素材'),
    sa.Column('model_platform', sa.String(length=100), nullable=True, comment='选择的模型平台'),
    sa.Column('model_id', sa.String(length=100), nullable=True, comment='选择的具体模型'),
    sa.Column('model_selection_mode', sa.Enum('auto', 'manual', name='model_selection_mode_enum'), nullable=False, comment='模型选择模式：auto（自动选择）/ manual（手动指定）'),
    sa.Column('max_concurrency', sa.Integer(), nullable=False, comment='本次任务最大并发数'),
    sa.Column('variable_values_json', sa.JSON(), nullable=True, comment='变量值JSON'),
    sa.Column('dedup_rules_json', sa.JSON(), nullable=True, comment='去重规则JSON'),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'cancelled', name='generation_task_status_enum'), nullable=False, comment='状态：pending（待处理）/ processing（处理中）/ completed（已完成）/ failed（失败）/ cancelled（已取消）'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='子任务总数'),
    sa.Column('queued_count', sa.Integer(), nullable=False, comment='队列中数量'),
    sa.Column('generating_count', sa.Integer(), nullable=False, comment='生成中数量'),
    sa.Column('completed_count', sa.Integer(), nullable=False, comment='已完成数'),
    sa.Column('failed_count', sa.Integer(), nullable=False, comment='失败数'),
    sa.Column('paused_count', sa.Integer(), nullable=False, comment='已暂停数量'),
    sa.Column('distributed_count', sa.Integer(), nullable=False, comment='已分发数量'),
    sa.Column('pending_publish_count', sa.Integer(), nullable=False, comment='待发布数量'),
    sa.Column('published_count', sa.Integer(), nullable=False, comment='已发布数量'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='发起者运营管理员ID'),
    sa.Column('owner_operator_id', sa.BigInteger(), nullable=False, comment='所属运营管理员ID（数据隔离用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['owner_operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_task_owner_operator_id'), 'generation_task', ['owner_operator_id'], unique=False)
    op.create_table('material_attachment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='素材ID'),
    sa.Column('file_type', sa.Enum('image', 'video', name='material_attachment_type_enum'), nullable=False, comment='文件类型：image（图片）/ video（视频）'),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='腾讯云COS文件URL'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小（字节）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('width', sa.Integer(), nullable=True, comment='图片/视频宽度（像素）'),
    sa.Column('height', sa.Integer(), nullable=True, comment='图片/视频高度（像素）'),
    sa.Column('duration', sa.Float(), nullable=True, comment='视频时长（秒）'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True, comment='缩略图URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_favorite',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='素材ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='收藏用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_tag_rel',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='素材ID'),
    sa.Column('tag_id', sa.BigInteger(), nullable=False, comment='标签ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['material_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('super_admin_id', sa.BigInteger(), nullable=True, comment='超级管理员ID'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='运营管理员ID'),
    sa.Column('sub_user_id', sa.BigInteger(), nullable=True, comment='子用户ID'),
    sa.Column('type', sa.Enum('task_completed', 'task_failed', 'cleanup_reminder', 'content_received', name='notification_type_enum'), nullable=False, comment='类型：task_completed / task_failed / cleanup_reminder / content_received'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='通知内容'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('related_id', sa.BigInteger(), nullable=True, comment='关联ID'),
    sa.Column('related_type', sa.String(length=100), nullable=True, comment='关联类型'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_user.id'], ),
    sa.ForeignKeyConstraint(['super_admin_id'], ['super_admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('super_admin_id', sa.BigInteger(), nullable=True, comment='超级管理员ID'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='运营管理员ID'),
    sa.Column('sub_user_id', sa.BigInteger(), nullable=True, comment='子用户ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作类型：create / update / delete / distribute / publish'),
    sa.Column('table_name', sa.String(length=100), nullable=True, comment='操作的数据表'),
    sa.Column('record_id', sa.BigInteger(), nullable=True, comment='操作的记录ID'),
    sa.Column('old_value_json', sa.JSON(), nullable=True, comment='操作前的旧值（JSON格式）'),
    sa.Column('new_value_json', sa.JSON(), nullable=True, comment='操作后的新值（JSON格式）'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='操作IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='浏览器/客户端信息'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_user.id'], ),
    sa.ForeignKeyConstraint(['super_admin_id'], ['super_admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publish_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('sub_user_id', sa.BigInteger(), nullable=False, comment='子用户ID'),
    sa.Column('platform', sa.String(length=100), nullable=False, comment='平台名称'),
    sa.Column('account_name', sa.String(length=255), nullable=False, comment='账号名称'),
    sa.Column('account_id', sa.String(length=255), nullable=True, comment='账号ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='模板名称'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='描述'),
    sa.Column('content_type', sa.Enum('text', 'image_text', 'video_text', name='template_content_type_enum'), nullable=False, comment='内容类型：text（纯文本）/ image_text（图文）/ video_text（视频）'),
    sa.Column('prompt_template', sa.Text(), nullable=True, comment='Prompt模板（支持变量占位符）'),
    sa.Column('variables_json', sa.JSON(), nullable=True, comment='变量定义JSON'),
    sa.Column('style_reference', sa.String(length=1000), nullable=True, comment='风格场景参考描述'),
    sa.Column('platform_rules_json', sa.JSON(), nullable=True, comment='平台适配规则JSON'),
    sa.Column('status', sa.Enum('enabled', 'disabled', name='template_status_enum'), nullable=False, comment='状态：enabled（已启用）/ disabled（已禁用）'),
    sa.Column('platform_id', sa.BigInteger(), nullable=True, comment='关联模板平台ID'),
    sa.Column('original_template_id', sa.BigInteger(), nullable=True, comment='原始模板ID（用于追踪克隆关系）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者运营管理员ID'),
    sa.Column('owner_operator_id', sa.BigInteger(), nullable=False, comment='所属运营管理员ID（数据隔离用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['original_template_id'], ['template.id'], ),
    sa.ForeignKeyConstraint(['owner_operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['template_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_owner_operator_id'), 'template', ['owner_operator_id'], unique=False)
    op.create_table('generation_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_id', sa.BigInteger(), nullable=False, comment='任务ID'),
    sa.Column('sub_user_id', sa.BigInteger(), nullable=False, comment='目标子用户ID'),
    sa.Column('template_id', sa.BigInteger(), nullable=True, comment='使用的模板'),
    sa.Column('model_platform', sa.String(length=100), nullable=True, comment='实际使用的模型平台'),
    sa.Column('model_id', sa.String(length=100), nullable=True, comment='实际使用的模型'),
    sa.Column('generated_title', sa.Text(), nullable=True, comment='生成的标题'),
    sa.Column('generated_text', sa.Text(), nullable=True, comment='生成的文本内容'),
    sa.Column('generated_image_urls_json', sa.JSON(), nullable=True, comment='生成的图片URL列表JSON'),
    sa.Column('generated_video_url', sa.String(length=500), nullable=True, comment='生成的视频URL'),
    sa.Column('status', sa.Enum('queued', 'generating', 'completed', 'failed', 'paused', name='generation_item_status_enum'), nullable=False, comment='生成状态：queued(待处理)/ generating(处理中)/ completed(已完成)/ failed(失败)/ paused(已暂停)'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('queued_at', sa.DateTime(), nullable=True, comment='进入队列时间'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始生成时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('distribution_status', sa.Enum('draft', 'ready', 'distributed', name='distribution_status_enum'), nullable=False, comment='分发状态：draft(草稿)/ ready(待分发)/ distributed(已分发)'),
    sa.Column('distributed_at', sa.DateTime(), nullable=True, comment='分发时间'),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True, comment='确认发布时间'),
    sa.Column('owner_operator_id', sa.BigInteger(), nullable=False, comment='所属运营管理员ID（数据隔离用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['owner_operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['generation_task.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_item_owner_operator_id'), 'generation_item', ['owner_operator_id'], unique=False)
    op.create_index(op.f('ix_generation_item_status'), 'generation_item', ['status'], unique=False)
    op.create_index(op.f('ix_generation_item_sub_user_id'), 'generation_item', ['sub_user_id'], unique=False)
    op.create_index(op.f('ix_generation_item_task_id'), 'generation_item', ['task_id'], unique=False)
    op.create_table('generation_task_progress_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_id', sa.BigInteger(), nullable=False, comment='任务ID'),
    sa.Column('queued_count', sa.Integer(), nullable=False, comment='队列中数量'),
    sa.Column('generating_count', sa.Integer(), nullable=False, comment='生成中数量'),
    sa.Column('completed_count', sa.Integer(), nullable=False, comment='已完成数量'),
    sa.Column('failed_count', sa.Integer(), nullable=False, comment='失败数量'),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'cancelled', name='generation_task_status_enum'), nullable=False, comment='任务状态'),
    sa.Column('progress_message', sa.String(length=1000), nullable=True, comment='进度信息'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录时间'),
    sa.ForeignKeyConstraint(['task_id'], ['generation_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_task_subuser',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_id', sa.BigInteger(), nullable=False, comment='任务ID'),
    sa.Column('sub_user_id', sa.BigInteger(), nullable=False, comment='子用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['generation_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_task_template',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_id', sa.BigInteger(), nullable=False, comment='任务ID'),
    sa.Column('template_id', sa.BigInteger(), nullable=False, comment='模板ID'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['task_id'], ['generation_task.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_tag_rel',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('template_id', sa.BigInteger(), nullable=False, comment='模板ID'),
    sa.Column('tag_id', sa.BigInteger(), nullable=False, comment='标签ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['tag_id'], ['template_tag.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_id', sa.BigInteger(), nullable=False, comment='任务ID'),
    sa.Column('generation_item_id', sa.BigInteger(), nullable=False, comment='分发的内容项'),
    sa.Column('sub_user_id', sa.BigInteger(), nullable=False, comment='接收的子用户ID'),
    sa.Column('publish_status', sa.Enum('distributed', 'pending_publish', 'published', name='publish_status_enum'), nullable=False, comment='发布状态：distributed / pending_publish / published'),
    sa.Column('distributed_at', sa.DateTime(), nullable=True, comment='分发时间'),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True, comment='确认发布时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['generation_item_id'], ['generation_item.id'], ),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['generation_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_sub_user_id'), 'distribution', ['sub_user_id'], unique=False)
    op.create_index(op.f('ix_distribution_task_id'), 'distribution', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distribution_task_id'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_sub_user_id'), table_name='distribution')
    op.drop_table('distribution')
    op.drop_table('template_tag_rel')
    op.drop_table('generation_task_template')
    op.drop_table('generation_task_subuser')
    op.drop_table('generation_task_progress_log')
    op.drop_index(op.f('ix_generation_item_task_id'), table_name='generation_item')
    op.drop_index(op.f('ix_generation_item_sub_user_id'), table_name='generation_item')
    op.drop_index(op.f('ix_generation_item_status'), table_name='generation_item')
    op.drop_index(op.f('ix_generation_item_owner_operator_id'), table_name='generation_item')
    op.drop_table('generation_item')
    op.drop_index(op.f('ix_template_owner_operator_id'), table_name='template')
    op.drop_table('template')
    op.drop_table('publish_account')
    op.drop_table('operation_log')
    op.drop_table('notification')
    op.drop_table('material_tag_rel')
    op.drop_table('material_favorite')
    op.drop_table('material_attachment')
    op.drop_index(op.f('ix_generation_task_owner_operator_id'), table_name='generation_task')
    op.drop_table('generation_task')
    op.drop_index(op.f('ix_template_platform_owner_operator_id'), table_name='template_platform')
    op.drop_table('template_platform')
    op.drop_index(op.f('ix_sub_user_userid'), table_name='sub_user')
    op.drop_index(op.f('ix_sub_user_status'), table_name='sub_user')
    op.drop_index(op.f('ix_sub_user_owner_operator_id'), table_name='sub_user')
    op.drop_index(op.f('ix_sub_user_managed_by'), table_name='sub_user')
    op.drop_table('sub_user')
    op.drop_index(op.f('ix_material_tag_owner_operator_id'), table_name='material_tag')
    op.drop_table('material_tag')
    op.drop_index(op.f('ix_material_owner_operator_id'), table_name='material')
    op.drop_table('material')
    op.drop_table('user_tag_rel')
    op.drop_index(op.f('ix_operator_userid'), table_name='operator')
    op.drop_index(op.f('ix_operator_status'), table_name='operator')
    op.drop_index(op.f('ix_operator_created_by'), table_name='operator')
    op.drop_table('operator')
    op.drop_table('model_config')
    op.drop_table('user_tag')
    op.drop_table('template_tag')
    op.drop_index(op.f('ix_super_admin_userid'), table_name='super_admin')
    op.drop_index(op.f('ix_super_admin_status'), table_name='super_admin')
    op.drop_table('super_admin')
    op.drop_table('cleanup_rule')
    # ### end Alembic commands ###
