"""
Fix material fields - add is_system to MaterialTag and library_type to Material

Revision ID: 20260415_0300
Revises: 20260415_0200
Create Date: 2025-04-15 03:00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20260415_0300'
down_revision: Union[str, None] = '20260415_0200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 为 material_tag 表添加 is_system 字段
    op.add_column(
        'material_tag',
        sa.Column(
            'is_system',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('0'),
            comment='是否系统默认标签（不可删除）'
        )
    )
    
    # 2. 为 material 表添加 library_type 字段
    op.add_column(
        'material',
        sa.Column(
            'library_type',
            sa.Enum('creation', 'benchmark', name='materiallibrary_type_enum'),
            nullable=False,
            server_default='benchmark',
            comment='素材库类型：creation（创作库）/ benchmark（对标库）'
        )
    )
    
    # 3. 创建索引以优化查询性能
    op.create_index(
        'ix_material_library_type',
        'material',
        ['library_type'],
        unique=False
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 删除索引
    op.drop_index('ix_material_library_type', table_name='material')
    
    # 2. 删除 library_type 字段
    op.drop_column('material', 'library_type')
    
    # 3. 删除 is_system 字段
    op.drop_column('material_tag', 'is_system')
    
    # ### end Alembic commands ###
