"""add super_admin display_name

Revision ID: 9b2d3c4e8f7a
Revises: 6cf171e7d573
Create Date: 2026-04-09 00:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2d3c4e8f7a'
down_revision: Union[str, None] = '6cf171e7d573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('super_admin', sa.Column('display_name', sa.String(length=100), nullable=True, comment='超级管理员自定义昵称'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('super_admin', 'display_name')
    # ### end Alembic commands ###
